# Generated by Django 4.2.3 on 2023-07-15 15:09

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[(0, 'Male'), (1, 'Female')], default=0, max_length=250)),
                ('state_of_origin', models.CharField(max_length=250)),
                ('local_origin', models.CharField(max_length=250)),
                ('Occupation', models.CharField(max_length=250)),
                ('marital_status', models.CharField(choices=[(0, 'Single'), (1, 'Married'), (2, 'Divored')], max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('mother_name', models.CharField(max_length=250)),
                ('contact_address', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('passport', models.ImageField(upload_to=account.models.passport_directory)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
