# Generated by Django 4.2.3 on 2023-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='marital_status',
            field=models.CharField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Divored')], max_length=250),
        ),
    ]
