# Generated by Django 4.0 on 2023-07-16 00:20

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_useraccount_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='passport',
            field=models.ImageField(upload_to=account.models.passport_directory),
        ),
    ]
