# Generated by Django 4.2 on 2023-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_useraccount_passport"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pdf_file", models.FileField(upload_to="pdfs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
