# Generated by Django 4.2 on 2023-08-30 16:03

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_generatedpdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedpdf",
            name="pdf_file",
            field=models.FileField(upload_to=account.models.pdf_dir),
        ),
    ]
